# Generated by Django 3.0 on 2022-08-25 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Especialidad')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Guardia',
                'verbose_name_plural': 'Guardias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('guardia', models.TextField(blank=True, verbose_name='Guardia')),
                ('activo', models.BooleanField(blank=True, default=False, null=True, verbose_name='Trae la Guardia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Historico de Guardia',
                'verbose_name_plural': 'Historicos de  Guardias',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Zona')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='SubEspecialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('especilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_especialidad', to='core.Especialidad', verbose_name='Especialidad')),
            ],
            options={
                'verbose_name': 'Sub-Especialidad',
                'verbose_name_plural': 'Sub-Especialidades',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la region')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_zona', to='core.Zona', verbose_name='Zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre del Especialista')),
                ('nivel', models.IntegerField(blank=True, choices=[(1, 'Especialista'), (2, 'Supervisor'), (3, 'Jefe de área'), (4, 'Gerente de área'), (5, 'Gerente')], null=True, verbose_name='Nivel Escalación')),
                ('phone_guardia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Guardia')),
                ('phone_asignado', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Asignado')),
                ('phone_otro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono de Otra Compañia')),
                ('fijo_oficina', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fijo Oficina')),
                ('fijo_casa', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fijo Casa')),
                ('guardia', models.ManyToManyField(blank=True, related_name='get_guardias', to='core.Guardia', verbose_name='Guardia')),
            ],
            options={
                'verbose_name': 'Especialista',
                'verbose_name_plural': 'Especialistas',
                'ordering': ['nivel'],
            },
        ),
        migrations.CreateModel(
            name='GuardiaEspecialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(blank=True, default=True, null=True, verbose_name='Trae la Guardia')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin')),
                ('guardia', models.TextField(blank=True, null=True, verbose_name='Guardia')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_especialistas', to='core.Profile', verbose_name='Seleccione el especialista')),
            ],
            options={
                'verbose_name': 'Guardia por Especialista',
                'verbose_name_plural': 'Guardias por Especialistas',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='guardia',
            name='sub_especilidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_sub_especilidad', to='core.SubEspecialidad', verbose_name='Sub-especilidad'),
        ),
    ]
