# Generated by Django 3.0 on 2022-09-10 01:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Historico',
        ),
        migrations.AlterModelOptions(
            name='especialidad',
            options={'ordering': ['name'], 'verbose_name': 'Especialidad', 'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='guardia',
            options={'ordering': ['name'], 'verbose_name': 'Guardia', 'verbose_name_plural': 'Guardias'},
        ),
        migrations.AlterModelOptions(
            name='guardiaespecialista',
            options={'ordering': ['name'], 'verbose_name': 'Guardia por Especialista', 'verbose_name_plural': 'Guardias por Especialistas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='subespecialidad',
            options={'ordering': ['name'], 'verbose_name': 'Sub-Especialidad', 'verbose_name_plural': 'Sub-Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='zona',
            options={'ordering': ['name'], 'verbose_name': 'Zona', 'verbose_name_plural': 'Zonas'},
        ),
        migrations.RenameField(
            model_name='subespecialidad',
            old_name='especilidad',
            new_name='especialidad',
        ),
        migrations.AddField(
            model_name='guardia',
            name='color_fondo',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True, verbose_name='Color de fondo'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='color_texto',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', max_length=18, null=True, verbose_name='Color del texto'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_region', to='core.Region', verbose_name='Región'),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email del Especialista'),
        ),
        migrations.AlterField(
            model_name='guardia',
            name='sub_especilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_sub_especilidad', to='core.SubEspecialidad', verbose_name='Sub-especilidad'),
        ),
        migrations.AlterField(
            model_name='guardiaespecialista',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='guardiaespecialista',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.RemoveField(
            model_name='guardiaespecialista',
            name='guardia',
        ),
        migrations.AddField(
            model_name='guardiaespecialista',
            name='guardia',
            field=models.ManyToManyField(blank=True, related_name='get_guardiasespecialistas', to='core.Guardia', verbose_name='Guardia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nivel',
            field=models.IntegerField(blank=True, choices=[(1, 'Especialista'), (2, 'Supervisor'), (3, 'Jefe de área'), (4, 'Gerente de área'), (5, 'Gerente')], null=True, verbose_name='Nivel de Escalamiento'),
        ),
        migrations.AlterField(
            model_name='region',
            name='zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='get_zona', to='core.Zona', verbose_name='Zona'),
        ),
    ]
