# Generated by Django 3.0 on 2022-09-10 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220909_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especialidad',
            name='created',
        ),
        migrations.RemoveField(
            model_name='especialidad',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='guardia',
            name='created',
        ),
        migrations.RemoveField(
            model_name='guardia',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='guardiaespecialista',
            name='created',
        ),
        migrations.RemoveField(
            model_name='guardiaespecialista',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='region',
            name='created',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='subespecialidad',
            name='created',
        ),
        migrations.RemoveField(
            model_name='subespecialidad',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='created',
        ),
        migrations.RemoveField(
            model_name='zona',
            name='updated',
        ),
    ]
