# Generated by Django 3.0 on 2022-09-20 20:31

import core.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220909_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardiaespecialista',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='guardiaespecialista',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fijo_casa',
            field=models.CharField(blank=True, help_text='Debe contener 11 digitos y empezar con 56', max_length=20, null=True, validators=[core.models.numeros_validos], verbose_name='Fijo Casa'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='fijo_oficina',
            field=models.CharField(blank=True, help_text='Debe contener 11 digitos y empezar con 56', max_length=20, null=True, validators=[core.models.numeros_validos], verbose_name='Fijo Oficina'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre del Especialista'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_asignado',
            field=models.CharField(blank=True, help_text='Debe contener 11 digitos y empezar con 56', max_length=20, null=True, validators=[core.models.numeros_validos], verbose_name='Teléfono Asignado'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_guardia',
            field=models.CharField(blank=True, help_text='Debe contener 11 digitos y empezar con 56', max_length=20, null=True, validators=[core.models.numeros_validos], verbose_name='Teléfono de Guardia'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_otro',
            field=models.CharField(blank=True, help_text='Debe contener 11 digitos y empezar con 56', max_length=20, null=True, validators=[core.models.numeros_validos], verbose_name='Teléfono de Otra Compañia'),
        ),
    ]
